Repository HO-CTO/sre-monitoring-as-code, pull requests merged in 2022-10, with the labels that each got.

#271 feat: modify sli for opensearch availability and latency
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/metric-types.libsonnet
Labels: enhancement, smoketest

#269 Add docs for run fmt and lint on save.
  .githooks/pre-commit
  .gitignore
  contributing.md
Labels: smoketest

#275 feat: add environment grouping to table panels
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
Labels: enhancement, smoketest

#280 278 slitype refactoring to support distinct objects and consistent dominations 1
  docs/source/get-started/index.html.md.erb
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-latency-using-seconds-target-metric.libsonnet
Labels: enhancement, smoketest

#286 Add Java and NodeJS example apps into the repo
  example-apps/sre-demo-java-app/.gitignore
  example-apps/sre-demo-java-app/.mvn/wrapper/maven-wrapper.jar
  example-apps/sre-demo-java-app/.mvn/wrapper/maven-wrapper.properties
  example-apps/sre-demo-java-app/Dockerfile
  example-apps/sre-demo-java-app/README.md
  example-apps/sre-demo-java-app/mvnw
  example-apps/sre-demo-java-app/mvnw.cmd
  example-apps/sre-demo-java-app/pom.xml
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricRestController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricService.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SreDemoJavaAppApplication.java
  example-apps/sre-demo-java-app/src/main/resources/application.properties
  example-apps/sre-demo-java-app/src/main/resources/templates/index.html
  example-apps/sre-demo-java-app/src/test/java/hocto/sredemojavaapp/SreDemoJavaAppApplicationTests.java
  example-apps/sre-demo-nodejs-app/.dockerignore
  example-apps/sre-demo-nodejs-app/.gitignore
  example-apps/sre-demo-nodejs-app/Dockerfile
  example-apps/sre-demo-nodejs-app/README.md
  example-apps/sre-demo-nodejs-app/index.js
  example-apps/sre-demo-nodejs-app/package-lock.json
  example-apps/sre-demo-nodejs-app/package.json
  example-apps/sre-demo-nodejs-app/views/index.html
Labels: smoketest

#273 Add hadolint into git pre-commit hooks
  .githooks/pre-commit
Labels: enhancement, smoketest

#284 Add Shellcheck to pre-commit hooks
  .githooks/pre-commit
  monitoring-as-code/run-mixin.sh
Labels: smoketest

#292 fix: change config docs to documentation
  .github/release-drafter.yml
Labels: bug

#290 Release 1.4.0
  .githooks/pre-commit
Labels: bug, minor, smoketest

#294 feat: update deploy docs workflow to use official github actions
  .github/workflows/deploy-docs.yml
Labels: enhancement

#295 293 spell checker for public facing docs
  .githooks/pre-commit
  .github/workflows/spellchecker.yml
  README.md
  contributing.md
  docs/README.md
  example-apps/sre-demo-java-app/README.md
  local/README.md
  monitoring-as-code/README.md
  monitoring-as-code/tools/spell-checker/.spellcheckerrc.yaml
  monitoring-as-code/tools/spell-checker/Dockerfile
  monitoring-as-code/tools/spell-checker/dictionary.txt
Labels: enhancement, smoketest

#300 Fix git add bug
  .githooks/pre-commit
Labels: bug, smoketest

#305 Fix spellchecker yml file
  .github/workflows/spellchecker.yml
Labels: bug, smoketest

#299 refractor: Product view sli title
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
Labels: smoketest, refactor

#306 Add LocalStack integration with MaC
  .githooks/pre-commit
  example-apps/localstack/.gitignore
  example-apps/localstack/README.md
  example-apps/localstack/arch-overview.png
  example-apps/localstack/docker-compose.yml
  example-apps/localstack/overview.drawio
  local/docker-compose.yaml
  local/yace/config/config.yml
Labels: enhancement, smoketest

#319 Update git version in Docker image.
  monitoring-as-code/Dockerfile
Labels: bug, smoketest

#312 Separate the example apps UI from their backend API
  example-apps/README.md
  example-apps/docker-compose.yml
  example-apps/sre-demo-frontend-app/.eslintrc.cjs
  example-apps/sre-demo-frontend-app/.gitignore
  example-apps/sre-demo-frontend-app/.prettierrc.json
  example-apps/sre-demo-frontend-app/Dockerfile
  example-apps/sre-demo-frontend-app/README.md
  example-apps/sre-demo-frontend-app/index.html
  example-apps/sre-demo-frontend-app/package-lock.json
  example-apps/sre-demo-frontend-app/package.json
  example-apps/sre-demo-frontend-app/public/favicon.ico
  example-apps/sre-demo-frontend-app/src/App.vue
  example-apps/sre-demo-frontend-app/src/assets/base.css
  example-apps/sre-demo-frontend-app/src/assets/logo.svg
  example-apps/sre-demo-frontend-app/src/assets/main.css
  example-apps/sre-demo-frontend-app/src/components/CounterForm.vue
  example-apps/sre-demo-frontend-app/src/components/Version.vue
  example-apps/sre-demo-frontend-app/src/main.js
  example-apps/sre-demo-frontend-app/vite.config.js
  example-apps/sre-demo-java-app/README.md
  example-apps/sre-demo-java-app/pom.xml
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricRestController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SimpleCounterMetricRequest.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SimpleCounterMetricResponse.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/VersionResponse.java
  example-apps/sre-demo-java-app/src/main/resources/application.properties
  example-apps/sre-demo-java-app/src/main/resources/templates/index.html
  example-apps/sre-demo-nodejs-app/README.md
  example-apps/sre-demo-nodejs-app/index.js
  example-apps/sre-demo-nodejs-app/package-lock.json
  example-apps/sre-demo-nodejs-app/package.json
Labels: enhancement, smoketest

#323 274 add metric types label
  example-apps/sre-demo-java-app/README.md
  local/yace/config/config.yml
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
Labels: enhancement, smoketest

#327 326 generic product view template filtering
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
Labels: smoketest, refactor

#321 Add workflow dispatch trigger
  .github/workflows/spellchecker.yml
Labels: smoketest

#325 Fix issues with YACE configuration
  example-apps/localstack/README.md
  local/docker-compose.yaml
  local/yace/config/config.yml
  monitoring-as-code/src/metric-types.libsonnet
Labels: bug, smoketest

#329 refactor: update workflow into different jobs
  .github/workflows/docker-build-branch.yml
Labels: minor, smoketest, refactor

#334 Remove platform specific references.
  local/alertmanager/config/platform-e-config.yaml
  local/alertmanager/config/platform-e-templates.tmpl
  local/alertmanager/config/start.sh
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/src/mac-config.libsonnet
Labels: bug

#338 335 improve mixin metric type docs
  docs/source/get-started/custom/index.html.md.erb
  docs/source/get-started/index.html.md.erb
Labels: documentation

#331 Add support for additional metric types in example apps.
  example-apps/README.md
  example-apps/sre-demo-frontend-app/index.html
  example-apps/sre-demo-frontend-app/package-lock.json
  example-apps/sre-demo-frontend-app/package.json
  example-apps/sre-demo-frontend-app/src/App.vue
  example-apps/sre-demo-frontend-app/src/components/ActionButtons.vue
  example-apps/sre-demo-frontend-app/src/components/ConfirmDialog.vue
  example-apps/sre-demo-frontend-app/src/components/CounterForm.vue
  example-apps/sre-demo-frontend-app/src/components/CounterTable.vue
  example-apps/sre-demo-frontend-app/src/components/GaugeTable.vue
  example-apps/sre-demo-frontend-app/src/components/HistogramTable.vue
  example-apps/sre-demo-frontend-app/src/components/IncDecGaugeForm.vue
  example-apps/sre-demo-frontend-app/src/components/IncrementCounterForm.vue
  example-apps/sre-demo-frontend-app/src/components/Modal.vue
  example-apps/sre-demo-frontend-app/src/components/Navbar.vue
  example-apps/sre-demo-frontend-app/src/components/NewCounterForm.vue
  example-apps/sre-demo-frontend-app/src/components/NewGaugeForm.vue
  example-apps/sre-demo-frontend-app/src/components/NewHistogramForm.vue
  example-apps/sre-demo-frontend-app/src/components/ObserveHistogramForm.vue
  example-apps/sre-demo-frontend-app/src/components/Version.vue
  example-apps/sre-demo-frontend-app/src/main.js
  example-apps/sre-demo-frontend-app/src/utils/axios.js
  example-apps/sre-demo-frontend-app/src/views/Counter.vue
  example-apps/sre-demo-frontend-app/src/views/Gauge.vue
  example-apps/sre-demo-frontend-app/src/views/Histogram.vue
  example-apps/sre-demo-frontend-app/src/views/Home.vue
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricRestController.java
  example-apps/sre-demo-nodejs-app/Dockerfile
  example-apps/sre-demo-nodejs-app/data/counterDAO.js
  example-apps/sre-demo-nodejs-app/data/gaugeDAO.js
  example-apps/sre-demo-nodejs-app/data/histogramDAO.js
  example-apps/sre-demo-nodejs-app/index.js
  example-apps/sre-demo-nodejs-app/package-lock.json
  example-apps/sre-demo-nodejs-app/package.json
  example-apps/sre-demo-nodejs-app/prometheus/index.js
  example-apps/sre-demo-nodejs-app/routes/counter.js
  example-apps/sre-demo-nodejs-app/routes/gauge.js
  example-apps/sre-demo-nodejs-app/routes/histogram.js
  example-apps/sre-demo-nodejs-app/service/counter.js
  example-apps/sre-demo-nodejs-app/service/gauge.js
  example-apps/sre-demo-nodejs-app/service/histogram.js
Labels: enhancement

#347 345 change panel colour when there is no sli data
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
Labels: enhancement

#349 feat: add-grafana-latency-and-sum-metrics and sli
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/metric-types.libsonnet
Labels: enhancement

#346 Update Java example to support Gauge and Histogram metrics
  example-apps/docker-compose.yml
  example-apps/sre-demo-frontend-app/Dockerfile
  example-apps/sre-demo-frontend-app/src/views/Counter.vue
  example-apps/sre-demo-frontend-app/src/views/Gauge.vue
  example-apps/sre-demo-frontend-app/src/views/Histogram.vue
  example-apps/sre-demo-java-app/Dockerfile
  example-apps/sre-demo-java-app/pom.xml
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricRestController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/MetricService.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SimpleCounterMetricRequest.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SimpleCounterMetricResponse.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/SreDemoJavaAppApplication.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/VersionResponse.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CounterController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CounterDAO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CounterIncrementRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CounterPOJO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CounterService.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/counter/CreateCounterRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/CreateGaugeRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/GaugeChangeRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/GaugeController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/GaugeDAO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/GaugePOJO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/gauge/GaugeService.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/CreateHistogramRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/HistogramController.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/HistogramDAO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/HistogramObserveRequestBody.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/HistogramPOJO.java
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/histogram/HistogramService.java
  example-apps/sre-demo-java-app/src/main/resources/application.properties
  example-apps/sre-demo-nodejs-app/data/counterDAO.js
  example-apps/sre-demo-nodejs-app/data/gaugeDAO.js
  example-apps/sre-demo-nodejs-app/data/histogramDAO.js
  example-apps/sre-demo-nodejs-app/service/counter.js
  example-apps/sre-demo-nodejs-app/service/gauge.js
  example-apps/sre-demo-nodejs-app/service/histogram.js
Labels: enhancement

#352 fix: grafana detail view latency
  monitoring-as-code/src/metric-types.libsonnet
Labels: bug
