Repository HO-CTO/sre-monitoring-as-code, pull requests merged in 2022-08, with the labels that each got.

#107 feat: pass mac_version var from gh workflow
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
  monitoring-as-code/Dockerfile
  monitoring-as-code/run-mixin.sh
Labels: smoketest

#108 32 configure dependabot scanning
  .github/dependabot.yml
Labels: good first issue

#106 101 update detail dashboard generation
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/detail-dashboard-elements-template.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-latency.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-avgovertime-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-correctness-cloudwatch-sqs-dlq.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-metric-library-template.libsonnet
  monitoring-as-code/src/util/sli-metric-library-functions.libsonnet
Labels: skip-release, smoketest

#120 refactor: moved metric config into new metric categories object and updated config items to be defined locally then exported
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
Labels: skip-release, smoketest

#122 refactor: renaming labels used for alert payload to match service now
  local/alertmanager/config/config.yaml
  monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
Labels: skip-release, smoketest

#124 115 dependabot refinement ignore packages like gitleaks action
  .github/dependabot.yml
Labels: enhancement

#127 refactor: update the categories and labels
  .github/release-drafter.yml
Labels: refactor

#125 refractor: remove and disable repo which are yet not supported by dep…
  .github/dependabot.yml
Labels: refactor

#131 113 auto release notes
  .github/release-drafter.yml
  .github/workflows/docker-build-tag.yml
Labels: enhancement

#130 refactor: renamed and moved slimetriclibs and metriccategories
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/src/sli-metric-config.libsonnet
  monitoring-as-code/src/util/sli-metric-library-functions.libsonnet
Labels: smoketest, refactor

#134 feat: added alert payload configuration item to mac config
  monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
Labels: enhancement, smoketest

#138 feat: added new metrics for rds read and write and sli types for average iops and throughput
  monitoring-as-code/src/sli-metric-config.libsonnet
Labels: enhancement, smoketest

#140 fix: detail dashboard config now uses metric type configs instead of sli types
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
Labels: smoketest

#142 refactor: add snyk steps to check docker image for vulnerabilities
  .github/workflows/docker-build-branch.yml
Labels: enhancement, smoketest

#148 145 update sli metric config
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/src/sli-metric-config.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-average-metric.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-avgovertime-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-correctness-cloudwatch-sqs-dlq.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-metric-library-template.libsonnet
  monitoring-as-code/src/util/sli-metric-library-functions.libsonnet
Labels: smoketest, refactor

#152 fix: allow workflow to write packages to GHCR
  .github/workflows/docker-build-branch.yml
Labels: bug, smoketest

#157 refactor: change weekly to daily checks and remove unsupported package docker-compose
  .github/dependabot.yml
Labels: refactor

#158 fix: replaced urls in monitoring mixin with localhost urls
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
Labels: patch, smoketest

#162 fix: updating localhost urls to have http prefix
  monitoring-as-code/src/mac-config.libsonnet
Labels: patch, smoketest

#168 fix: correct sql metric naming and labels
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
Labels: bug

#160 fix: http requests availability now works with just errorstatus or resource labels
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
Labels: bug, smoketest

#172 refactor: add dependencies label to release drafter
  .github/release-drafter.yml
Labels: minor, smoketest, refactor

#174 refactor: Update Docker Build Tag Workflow
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
Labels: minor, smoketest, refactor

#176 fix: remove 'v' version from the config
  .github/release-drafter.yml
Labels: bug, minor, smoketest

#179 169 update sli metric libraries
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-availability-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-average-metric.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-avgovertime-generic.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-correctness-cloudwatch-sqs-dlq.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-cloudwatch-alb.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-latency-promclient.libsonnet
  monitoring-as-code/src/sli-metric-libraries/sli-metric-library-template.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-correctness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-using-single-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/histogram-quantile-latency.libsonnet
  monitoring-as-code/src/sli-value-libraries/max-latency-using-cloudwatch-percentile-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-bad-request-metrics.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-failure-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-label.libsonnet
  monitoring-as-code/src/sli-value-libraries/sli-value-library-template.libsonnet
  monitoring-as-code/src/util/sli-value-library-functions.libsonnet
Labels: smoketest, refactor

#181 feat: added new opensearch metrics and availablity sli type
  monitoring-as-code/src/metric-types.libsonnet
Labels: enhancement, smoketest

#183 refactor: giving target metrics for detail dashboard elements better names
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/detail-dashboard-elements-template.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-latency.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
Labels: smoketest, refactor

#178 refactor: add docker image scan to the workflow
  .github/workflows/docker-build-branch.yml
  monitoring-as-code/Dockerfile
  monitoring-as-code/run-mixin.sh
Labels: smoketest, refactor

#188 187 update readme installation and useage instructions
  monitoring-as-code/README.md
Labels: enhancement, minor, smoketest

#191 190 add multi sli type
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
  monitoring-as-code/src/alerts/burn-rate-rules.libsonnet
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
Labels: enhancement, smoketest

#194 feat: added testing mixin
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
Labels: enhancement, smoketest

#196 fix: fixed typo for aws sqs
  monitoring-as-code/src/metric-types.libsonnet
Labels: bug, smoketest

#201 feat: added sli value libraries for nginx generic approach
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/sli-value-libraries/generic-histogram-quantile-latency.libsonnet
  monitoring-as-code/src/sli-value-libraries/generic-proportion-of-errors-using-label.libsonnet
  monitoring-as-code/src/util/sli-value-library-functions.libsonnet
Labels: enhancement, smoketest

#204 fix: added gitkeep to output directory and updated gitignore
  .gitignore
  monitoring-as-code/output/.gitkeep
Labels: bug

#192 feat: run automation test by run mixin and validate the rules file vi…
  .github/workflows/docker-build-branch.yml
Labels: enhancement, smoketest

#205 202 update all sli value libraries and alerts for generic poc
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
  monitoring-as-code/src/alerts/burn-rate-rules.libsonnet
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-correctness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-using-single-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/generic-histogram-quantile-latency.libsonnet
  monitoring-as-code/src/sli-value-libraries/generic-proportion-of-errors-using-label.libsonnet
  monitoring-as-code/src/sli-value-libraries/histogram-quantile-latency.libsonnet
  monitoring-as-code/src/sli-value-libraries/max-latency-using-cloudwatch-percentile-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-bad-request-metrics.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-failure-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-label.libsonnet
  monitoring-as-code/src/sli-value-libraries/sli-value-library-template.libsonnet
  monitoring-as-code/src/util/sli-value-library-functions.libsonnet
Labels: enhancement, smoketest
