Repository HO-CTO/sre-monitoring-as-code, pull requests merged in 2022-09, with the labels that each got.

#207 206 update summary dashboard
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
Labels: enhancement, smoketest

#211 fix: combine snyk container scans into one stage
  .github/workflows/docker-build-branch.yml
Labels: bug, smoketest

#214 185 document monitoring as code features
  docs/source/features/index.html.md.erb
  docs/source/get-started/index.html.md.erb
Labels: documentation, enhancement

#219 feat: add Hadolint Dockerfile linting tool
  .github/workflows/docker-build-branch.yml
Labels: enhancement, smoketest

#224 202 journey view redesign
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
Labels: smoketest, refactor

#241 bug: update snyk docker action to snyk cli
  .github/workflows/docker-build-branch.yml
Labels: bug, smoketest

#230 202 journey view redesign (#224)
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
Labels: smoketest

#231 213 mac product view redesign (#220)
  monitoring-as-code/deploy.sh
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
Labels: smoketest

#234 Add jsonnetfmt check into pipeline. (#228)
  .github/workflows/docker-build-branch.yml
  monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
  monitoring-as-code/src/alerts/burn-rate-rules.libsonnet
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/detail-dashboard-elements-template.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-latency.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
  monitoring-as-code/src/lib/sli-element-functions.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
  monitoring-as-code/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-correctness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-using-single-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/histogram-quantile-latency.libsonnet
  monitoring-as-code/src/sli-value-libraries/max-latency-using-cloudwatch-percentile-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-bad-request-metrics.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-failure-metric.libsonnet
  monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-label.libsonnet
  monitoring-as-code/src/sli-value-libraries/sli-value-library-template.libsonnet
  monitoring-as-code/src/util/sli-value-library-functions.libsonnet
  monitoring-as-code/src/util/string-formatting-functions.libsonnet
Labels: enhancement, smoketest

#248 229 jsonnet lint (#236)
  .github/workflows/docker-build-branch.yml
  monitoring-as-code/src/dashboards/detail-dashboard-elements/detail-dashboard-elements-template.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/sli-value-libraries/sli-value-library-template.libsonnet
Labels: enhancement, smoketest

#245 244 summary view redesign fired alerts
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
Labels: enhancement, smoketest

#232 Add debug utility function (#225)
  contributing.md
  monitoring-as-code/src/util/debug.libsonnet
Labels: enhancement, smoketest

#251 fix: correct git clone repo url
  local/README.md
  monitoring-as-code/README.md
Labels: bug

#247 Update gemfile with haml ver 5.x
  docs/Gemfile
Labels: bug, minor, smoketest

#259 feat: add product view navigation to summary screen
  monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
Labels: enhancement, smoketest

#263 refactor: update workflow to use jsonnet fmt/lint container image
  .github/workflows/docker-build-branch.yml
  monitoring-as-code/fmt.sh
  monitoring-as-code/lint.sh
Labels: smoketest, refactor

#265 264 freshness sli value denominator using wrong function
  monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
Labels: bug

#261 bug: rename stanza to journey1 in testing mixin
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/mixin-builder.libsonnet
Labels: bug, smoketest

#256 add read latency sli for rds
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/metric-types.libsonnet
  monitoring-as-code/src/sli-value-libraries/average-latency-using-seconds-target-metric.libsonnet
Labels: enhancement, smoketest
