Repository HO-CTO/sre-monitoring-as-code, pull requests merged in 2022-07, with the labels that each got.

#64 feat: migrate monitoring-local source code to github
  local/.gitignore
  local/README.md
  local/alertmanager/config/config.yaml
  local/alertmanager/config/ebsa-config.yaml
  local/alertmanager/config/ebsa-templates.tmpl
  local/alertmanager/config/start.sh
  local/cloudwatch-exporter/config.yml
  local/docker-compose.yaml
  local/grafana/grafana.env
  local/grafana/provisioning/dashboards/config.yml
  local/grafana/provisioning/datasources/datasource.yml
  local/prometheus/file_sd_configs/cloudwatch_targets.json
  local/prometheus/file_sd_configs/monitoring_product_targets.json
  local/prometheus/prometheus1.yaml
  local/prometheus/prometheus2.yaml
  local/prometheus/rule_configs/.gitkeep
  local/thanos/bucket_config.yaml
  local/yace/config/config.yml
  local/yace/config/start.sh
Labels: enhancement

#66 feat: migrate monitoring-as-code source code to github without history
  monitoring-as-code/.gitignore
  monitoring-as-code/Dockerfile
  monitoring-as-code/README.md
  monitoring-as-code/deploy.sh
  monitoring-as-code/monitoring-config/mixin-defs/monitoring-mixin.jsonnet
  monitoring-as-code/monitoring-config/mixin-defs/summary-mixin.jsonnet
  monitoring-as-code/monitoring-config/src/alerts/burn-rate-alerts.libsonnet
  monitoring-as-code/monitoring-config/src/alerts/burn-rate-rules.libsonnet
  monitoring-as-code/monitoring-config/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/monitoring-config/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/monitoring-config/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/monitoring-config/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/monitoring-config/src/dashboards/summary-dashboard.libsonnet
  monitoring-as-code/monitoring-config/src/lib/alert-functions.libsonnet
  monitoring-as-code/monitoring-config/src/lib/dashboard-functions.libsonnet
  monitoring-as-code/monitoring-config/src/lib/mixin-functions.libsonnet
  monitoring-as-code/monitoring-config/src/lib/sli-element-functions.libsonnet
  monitoring-as-code/monitoring-config/src/mac-config.libsonnet
  monitoring-as-code/monitoring-config/src/mixin-builder.libsonnet
  monitoring-as-code/monitoring-config/src/sli-elements/recording-rules.libsonnet
  monitoring-as-code/monitoring-config/src/sli-elements/sli-standard-elements.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-availability-cloudwatch-alb.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-availability-generic.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-availability-promclient.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-avgovertime-generic.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-correctness-cloudwatch-sqs-dlq.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-latency-cloudwatch-alb.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-latency-promclient.libsonnet
  monitoring-as-code/monitoring-config/src/sli-metric-libraries/sli-metric-library-template.libsonnet
  monitoring-as-code/monitoring-config/src/util/sli-metric-library-functions.libsonnet
  monitoring-as-code/monitoring-config/src/util/string-formatting-functions.libsonnet
  monitoring-as-code/run-mixin.sh
Labels: enhancement

#96 refactor: rename docker image name
  monitoring-as-code/README.md
  monitoring-as-code/deploy.sh
Labels: docker

#102 94 container image build and push
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
Labels: smoketest

#103 Refactor: deploy script now copies output to corresponding local directories
  monitoring-as-code/deploy.sh
Labels: major
