Repository HO-CTO/sre-monitoring-as-code, pull requests merged in 2022-11, with the labels that each got.

#343 refactor: update workflow into different jobs
  .github/workflows/docker-build-tag.yml
Labels: refactor

#355 Remove references to queue_type.
  monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
  monitoring-as-code/src/metric-types.libsonnet
Labels: refactor

#362 feat: add documentation panel to dashboards
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
  monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
  monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
  monitoring-as-code/src/dashboards/overview-dashboard.libsonnet
  monitoring-as-code/src/dashboards/product-dashboard.libsonnet
  monitoring-as-code/src/mac-config.libsonnet
Labels: enhancement

#366 Change phase and header link
  docs/config/tech-docs.yml
Labels: documentation

#368 Add health indicator status metric to Java app.
  example-apps/sre-demo-java-app/src/main/java/hocto/sredemojavaapp/HealthMetricsExportConfiguration.java
Labels: enhancement

#370 369 render diagrams
  .github/workflows/deploy-docs.yml
  docs/README.md
  docs/monitoring_as_code.drawio
  docs/source/get-started/index.html.md.erb
  docs/source/images/dashboard-hierarchy.png
  docs/source/images/detail-view.png
  docs/source/images/journey-view.png
  docs/source/images/monaco-benefits.png
  docs/source/images/monaco-how-it-works.png
  docs/source/images/monaco-pg-lld.drawio.png
  docs/source/images/product-view.png
  docs/source/images/responding-to-alerts.png
  docs/source/index.html.md.erb
  docs/source/monitor-your-service/index.html.md.erb
  docs/source/responding-to-alerts/index.html.md.erb
Labels: enhancement

#380 Optimise trufflehog pre-push scan.
  .githooks/pre-push
Labels: bug

#376 Refactor frontend of example apps
  example-apps/sre-demo-frontend-app/package.json
  example-apps/sre-demo-frontend-app/src/components/CounterTable.vue
  example-apps/sre-demo-frontend-app/src/components/HistogramTable.vue
  example-apps/sre-demo-frontend-app/src/components/MetricTable.vue
  example-apps/sre-demo-frontend-app/src/components/Modal.vue
  example-apps/sre-demo-frontend-app/src/utils/splitLabels.js
  example-apps/sre-demo-frontend-app/src/utils/splitLabels.test.js
  example-apps/sre-demo-frontend-app/src/views/Counter.vue
  example-apps/sre-demo-frontend-app/src/views/Gauge.vue
  example-apps/sre-demo-frontend-app/src/views/Histogram.vue
  example-apps/sre-demo-nodejs-app/index.js
  example-apps/sre-demo-nodejs-app/service/histogram.js
Labels: refactor

#381 refractor: links to docs
  docs/source/get-started/install/index.html.md.erb
  monitoring-as-code/tools/spell-checker/dictionary.txt
Labels: documentation

#373 feat: add scheduler main workflow
  .github/workflows/scheduler-main.yml
Labels: enhancement

#387 refactor: update scheduler workflow and rename other filenames/workflows
  .github/workflows/feature.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: refactor

#385 fix: action render diagrams on all docs changes
  .github/workflows/deploy-docs.yml
Labels: bug

#389 docs: root readme dir structure update
  README.md
Labels: documentation, refactor

#400 feat: add instructions to render diagrams locally
  docs/README.md
Labels: enhancement

#399 refactor: hardcode colour black
  monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
Labels: refactor

#401 feat: add nodejs metric
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
  monitoring-as-code/mixin-defs/testing-mixin.jsonnet
  monitoring-as-code/src/metric-types.libsonnet
Labels: enhancement

#403 fix: update if condition to reflect the job status
  .github/workflows/main.yml
Labels: bug

#407 350 add database to example demo apps
  example-apps/README.md
  example-apps/docker-compose.yml
Labels: enhancement

#404 393 refine mac public documentation
  .gitignore
  docs/Dockerfile
  docs/Gemfile
  docs/Gemfile.lock
  docs/source/adopting-mac/index.html.md.erb
  docs/source/adopting-mac/interpret-mac/index.html.md.erb
  docs/source/adopting-mac/monitor-your-service/index.html.md.erb
  docs/source/adopting-mac/responding-to-alerts/index.html.md.erb
  docs/source/advanced/custom/index.html.md.erb
  docs/source/advanced/index.html.md.erb
  docs/source/get-started/define-sli/index.html.md.erb
  docs/source/get-started/index.html.md.erb
  docs/source/get-started/install/index.html.md.erb
  docs/source/index.html.md.erb
  docs/source/learn-mac/architecture/index.html.md.erb
  docs/source/learn-mac/features/index.html.md.erb
  docs/source/learn-mac/index.html.md.erb
  docs/source/learn-mac/sre-with-slo/index.html.md.erb
Labels: documentation

#421 Add platforms to gem file
  docs/Gemfile.lock
Labels: bug

#427 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#423 Add release workflow to contributing guide.
  contributing.md
Labels: documentation

#414 refactor: update generic mixing file into golden sli category
  monitoring-as-code/mixin-defs/generic-mixin.jsonnet
Labels: refactor

#419 Extract container building and testing into workflow.
  .github/workflows/build-container-image.yml
  .github/workflows/feature.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: minor, refactor

#433 Remove reference to incorrect workflow.
  .github/workflows/main.yml
Labels: bug
